## This program demonstrates how to use the geometry module

In [1]:
import numpy as np
from scipy.spatial.transform import Rotation as R
#from src.software.utils.visionUtils import getIsometry

SyntaxError: invalid syntax (935369556.py, line 3)

In [2]:
def getIsometry(rotation, translation):
    return np.vstack([np.hstack([rotation,translation.reshape(3,-1)]), [0, 0, 0, 1]])

### The Geometry module provides a variety of rotation and translation representations using Numpy

In [3]:
rotation_matrix = R.identity().as_matrix()
print("Identity Rotation matrix = \n", rotation_matrix)

Identity Rotation matrix = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Read numpy Euler Matrix [3, 3] and Reperesent as Quatranion [x, y, z, w]

In [4]:
r = R.from_matrix(rotation_matrix)
r.as_quat()

array([0., 0., 0., 1.])

### Rotate 45 degrees along the Z axis

In [5]:
rot = R.from_euler('z', 45, degrees=True)
rot_mat = rot.as_matrix()
rot_mat

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

### Coordinate transformation with AngleAxis

In [6]:
v_rotated = rot_mat @ np.asarray([1, 0, 0])
print("(1,0,0) after rotation (by angle axis) = ", v_rotated)

(1,0,0) after rotation (by angle axis) =  [0.70710678 0.70710678 0.        ]


### Coordinate transformation with Rotation Matrix

In [7]:
v_rotated = rot_mat @ np.asarray([1, 0, 0])
print("(1,0,0) after rotation (by matrix) = ", v_rotated)

(1,0,0) after rotation (by matrix) =  [0.70710678 0.70710678 0.        ]


### Convertion of the rotation matrix directly into Euler angles

In [8]:
euler_angles = rot.as_euler('xyz')
print("yaw pitch roll = ", np.flip(euler_angles))

yaw pitch roll =  [0.78539816 0.         0.        ]


### Euclidean transformation matrix using Numpy

In [9]:
translation = np.asarray([1, 3, 4])
T = getIsometry(rot_mat, translation)
print("Transform matrix = \n", T)

Transform matrix = 
 [[ 0.70710678 -0.70710678  0.          1.        ]
 [ 0.70710678  0.70710678  0.          3.        ]
 [ 0.          0.          1.          4.        ]
 [ 0.          0.          0.          1.        ]]


###  Use the transformation matrix for coordinate transformation

In [10]:
v_transformed = T @ np.asarray([1, 0, 0, 1])
print("v tranformed = ", v_transformed[:3])

v tranformed =  [1.70710678 3.70710678 4.        ]
